---
title: "The most adecuate Car for your trip"
author: "Carlos Barco"
date: "9/28/2017"
output:
  slidy_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

Welcome to visit us.

The sites is providing a tool to illustrate the Fuel-efficiency ratings of your Dream automobile.

## How to use the app

First, provide your trip detail like distance of your trip and the price od gasoline in your region, it's needed to calculate the Gasoline Expenditure for each car. Next with provide your budget on gasoline, so we can filtered and show the car with has Miles per Gallon (MPG) that below your budget.

Second, you can choose your desire cars characteristic in term of : Cylinders, Displacement, Horse Power and Transmission. 

The result contains filters selected cars will show in a table on the main content with using the mtcars dataset from [R].
You can sort the table according to the variable you want by clicking the arrows at the top of the table.

## Github repository

Source code for ui.R and server.R files are available on the GitHub repo: https://github.com/a4user1/Developing-Data-Products
  
  
Thank you, and enjoy using this service.  

## Customer service  
Any comments?,  
please send it to [Carlos](carlosbarcoblanco@icloud.com)